# Generated by Django 5.2.6 on 2025-09-19 23:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор кошелька (UUID).', primary_key=True, serialize=False, unique=True)),
                ('balance', models.BigIntegerField(default=0, help_text='Текущий баланс в минимальных единицах валюты (например, копейках).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время создания кошелька.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения кошелька.')),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
                'db_table': 'wallets',
            },
        ),
    ]
